### ISSUE TITLE
Allow size adjustment of tiled windows

### ISSUE THREAD

**Issue by PeteS4** [Fmstrat/wintile#20]
Right now, when manually resizing a tiled window it jumps back to its original size and position instead of staying tiled. In Windows and Gnome without this addon, one can resize the tiled window and the adjacent window will grow or shrink accordingly. Would it be possible to add the same behaviour to this addon?

**Comment by Fmstrat** [comment]
Ahh, yes. This is certainly something it should do. I'll put it in for the next release.

**Comment by igordovgaluk** [comment]
@Fmstrat would be great to have the feature. Without it the extension adds confusion to UX.

**Comment by ermo** [comment]
@Fmstrat FWIW, #2 was meant to include this too...

**Comment by farefernandez** [comment]
It would be great to have this!! Are there plans to make a new release?

Thanks for this great piece of software! I use it with a 3-column layout and it's really a good way to take advantage of wider monitors.

**Comment by rvillablanca** [comment]
Very nice extension. We are waiting for this helpful feature :100:

**Comment by jlost** [comment]
Would love to have this.

**Comment by Fmstrat** [comment]
Hey guys, just an update since there have been recent comments. I've been thinking about this and the tough part is going to be managing all the different column counts. I'm debating on a rewrite that uses a calculated grid instead, which would make this much, much easier. Unfortunately I haven't had a lot of time to dedicate to this particular project lately.

**Comment by jlost** [comment]
I would be satisfied even if the windows just retained their dimensions when you manually resized them - see attached screencast, I try to adjust window size from a tiled position and it snaps back to its pre-tiled state.
https://streamable.com/j8jo6x

**Comment by ba32107** [comment]
I believe the original description describes two separate issues.

> Right now, when manually resizing a tiled window it jumps back to its original size and position instead of staying tiled. 

This is a bug, and it's the same thing @jlost described in the above comment, and what's visible on the screencast.

> In Windows and Gnome without this addon, one can resize the tiled window and the adjacent window will grow or shrink accordingly.

If I understand correctly, what @PeteS4 means here is that if you have multiple tiled windows (e.g. 2 half-screen sized windows, next to each other), then he would like both windows to resize accordingly, when he resizes one of them. E.g. when one of the windows is enlarged, the other one would shrink automatically. Is that correct?

I think these are two separate issues. Fixing the bug is a prerequisite for tackling the second issue (which is actually a feature request).

**Comment by PeteS4** [comment]
Yes. I was not sure if the first issue is a bug or intended behavior to prevent tiled windows from overlapping with other tiling areas. Therefore I added the second part to show how other tiling engines handle this issue.

**Comment by adosar** [comment]
Is the feature added?

**Comment by GrylledCheez** [comment]
fixed in v10 #101
