### ISSUE TITLE
[enhancement] Reduce minimum delay to 0 + fix minor typo

### ISSUE THREAD

**Issue by elliotwutingfeng** [Fmstrat/wintile#22]
Is it possible to reduce the minimum allowed value for the preferences field "Delay in ms before preview displays" to 0 instead of 100? This would allow me to "flick" windows to the edges without having to wait ~100ms for the tiling preview to appear (the actual observed latency may be even more than 100ms).

I also found a minor typo, "displays" was spelt as "dislpays" as of version 5.

**Comment by ba32107** [comment]
I believe this should be doable, but will leave it up to @Fmstrat to make that decision, I am not sure if there is any reason behind having 100ms as a minimum value.

I've opened a PR to fix the typo.

**Comment by loligans** [comment]
I went ahead and did this here: https://github.com/loligans/wintile/commit/1889cced37ce824779e350aaa260125e10f00b60

I ran into a problem setting the delay to 0ms. When the delay is 0ms gnome-shell will freeze. So instead of 0ms I opted for 25ms as the minimum which satisfies my desire for perceived responsiveness.
