### ISSUE TITLE
Clicking on windows near top of screen activates WinTile

### ISSUE THREAD

**Issue by Fmstrat** [Fmstrat/wintile#33]
When clicking on a window title bar near the top of the screen, it activates WinTile. This could be due to the reduced delay time to 25ms. Needs investigation.

**Comment by Fmstrat** [comment]
Potential cause: https://github.com/Fmstrat/wintile/pull/27

**Comment by Fmstrat** [comment]
@loligans Could you validate this? I have found that clicking a title bar of say, a maximized window towards the right hand side instantly locks it to top 1/4 screen without a drag. And sometimes clicking X on a window that isn't active will move the active window to that tile location.

**Comment by loligans** [comment]
I'm at work right now, but I suspect that when the following conditions are met an accidental resize operation might occur:
- When the cursor is close enough to an edge or corner. (Within the area to trigger a resize)
- And the user initiates a window drag operation.
- Then the resize operation gets triggered.

The bug has likely been hidden all along because the delay was much longer. Since the delay to resize has been decreased it makes this bug more obvious.

**Comment by Fmstrat** [comment]
Well, I wouldn't say it was a bug before :) The more I think about it I'm pretty sure that's why I had the delay set longer than a standard "click time". I will investigate to be sure.

**Comment by GrylledCheez** [comment]
This issue seems to be closed.
Please reopen if it's still an issue.
