### ISSUE TITLE
How to install it?

### ISSUE THREAD

**Issue by krishnaap** [Fmstrat/wintile#63]
Installation instructions aren't clear. Could you elaborate on how to install it properly?

**Comment by Vistaus** [comment]
You can install it easily from the GNOME Extensions site: https://extensions.gnome.org/extension/1723/wintile-windows-10-window-tiling-for-gnome/

**Comment by shanto12** [comment]
installation instructions again not clear. Go to the gnome extension page and do what? All I can do from there is to download a .zip file. Not sure what to do after that.

**Comment by Vistaus** [comment]
If you only get the option to download a zip file, you're most likely using an unsupported browser. Otherwise the extension would get installed instead of point you to the .zip file.

Either way: even the .zip file is easily installable. Just open up GNOME Tweaks, go to the extensions page, choose to manually install an extension and choose the zip file. It should then be installed manually.

Another option (if you don't mind installing a third-party tool) is to use GNOME Extension Manager: https://www.omgubuntu.co.uk/2022/01/gnome-extension-manager-app-easy-install

---------------

Either way, the installation instructions are clear. Most browsers are supported by the GNOME Extensions website and give you the option to do a 1-click install.

**Comment by SOSANA** [comment]
For anyone in the future coming across this with issues for manual install follow this tutorial [here](https://www.debugpoint.com/manual-installation-gnome-extension/).

As well make sure to add "42.0" to metadata.json

**Comment by mauriciogracia** [comment]
Can you please include the above instructions in the README of the repository root ?

I just went through the steps of trying to add a ZIP extension in Gnome, just to realize that I was using gnome-shell-extensions instead of gnome-extensions

**Comment by timoshishi** [comment]
This process worked for me on Ubuntu 22.04

1. Install Extension Manager flatpak from [flathub](https://flathub.org/apps/details/com.mattjakeman.ExtensionManager)
2. Download shell version 40, extension v7 of WinTile from the [gnome extensions website](https://extensions.gnome.org/extension/1723/wintile-windows-10-window-tiling-for-gnome/)
3. Unpack zipfile
4. Change manifest.json in the unpacked folder to include shell versions 42.0 as well as my current shell version got from terminal with `gnome-shell --version`
5. Follow [this guide on how to install a package manually](https://www.pragmaticlinux.com/2021/06/manually-install-a-gnome-shell-extension-from-a-zip-file/) through renaming and moving the unzipped folder
6. Log out and log back in (Wayland does not allow you to restart with the command listed in the guide)
7. Open Extension Manager and you should see WinTile under the User-Installed Extensions section above the System Extensions in the installed area.

**Comment by GrylledCheez** [comment]
Installation instructions have been added to the README.md
